# Docker Development Configuration

services:
  auth-service-dev:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    env_file:
      - .env
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - auth-network
    restart: unless-stopped

  mongodb:
    image: mongo:7
    container_name: auth_mongodb_dev
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin_password
      - MONGO_INITDB_DATABASE=auth_db
    volumes:
      - auth_mongodb_data_dev:/data/db
      - auth_mongodb_config_dev:/data/configdb
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - auth-network
    restart: unless-stopped

  mongo-express:
    image: mongo-express:1.0.2
    container_name: auth_mongo_express_dev
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin_password
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongodb
    networks:
      - auth-network
    restart: unless-stopped

networks:
  auth-network:
    driver: bridge

volumes:
  auth_mongodb_data_dev:
    name: auth_service_mongodb_data_dev
  auth_mongodb_config_dev:
    name: auth_service_mongodb_config_dev
